spring:
  application:
    name: cosmos-kotlin-demo

azure:
  cosmos:
    endpoint: https://localhost:8081   # e.g. https://<your-account>.documents.azure.com:443/
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==             # primary key
    database: demo-db
    # Optional tuning:
    consistency-level: EVENTUAL
    # preferred-regions: West US,East US
    response-diagnostics-enabled: true

logging:
  level:
    root: INFO
    com.azure: WARN
    com.azure.spring.data.cosmos: INFO
